/**
 * Shared domain types.
 *
 * PROTOTYPE ONLY. Every patient in this app is synthetic and generated by
 * src/lib/seed.ts. No real PHI/PII exists anywhere in this repository.
 */

export type Sex = "M" | "F";

/**
 * Physiological age band. Determines which early-warning chart applies —
 * see src/lib/ews.ts. Adult thresholds are not valid for children and
 * under-read deterioration in the elderly.
 */
export type AgeBand =
  | "infant"
  | "toddler"
  | "child"
  | "adolescent"
  | "adult"
  | "older adult";

/**
 * What the hospital already knows about this patient before they open their
 * mouth. Roughly half of arrivals have something on file and half have nothing;
 * the triage assistant has to behave safely in both cases, and must never treat
 * "no history recorded" as "no history exists".
 */
export interface PriorRecord {
  /** Prior encounters on file. */
  previousVisits: number;
  /** Known conditions, as the record holds them. */
  conditions: string[];
  /** Current medications, which are themselves risk signals. */
  medications: string[];
  /** Documented allergies. */
  allergies: string[];
  /** A personal care plan for a chronic condition, if one exists. */
  carePlan: string | null;
  /** Simulated-minutes-ago the record was last updated. */
  lastUpdatedMinutesAgo: number;
}

/**
 * How much of the intake picture is actually present.
 *
 * Drives the precautionary uplift: an incomplete picture is a reason to
 * escalate, never a reason to relax. Missing data is not reassuring data.
 */
export interface DataCompleteness {
  /** 0..1 — proportion of the expected intake fields that are populated. */
  score: number;
  /** Human-readable list of what is missing. */
  missing: string[];
  hasPriorRecord: boolean;
  hasFullVitals: boolean;
  /** True when this is a first presentation with nothing on file. */
  zeroHistory: boolean;
}

/**
 * How the patient reached the department.
 *
 * This is an ENCOUNTER fact, not a patient attribute: it says nothing about who
 * someone is, only about how they arrived. It is on every triage form in the
 * world and is safe to hold and to aggregate.
 *
 * It replaces the demographic tag this prototype previously carried. No
 * ethnicity, community, region, religion, language, caste or payer field is
 * recorded anywhere in this codebase, and the audit does not need one: the
 * override layer can be held to account against arrival route and against the
 * patient's own measured physiology, neither of which requires profiling anyone.
 *
 * Arrival route is itself a well-documented source of triage bias — patients who
 * walk in are systematically under-triaged relative to identical patients who
 * arrive by ambulance, because the mode of arrival anchors the assessor.
 */
export type ArrivalMode = "Walk-in" | "Ambulance" | "Referred";

export const ARRIVAL_MODES: ArrivalMode[] = ["Walk-in", "Ambulance", "Referred"];

export interface Vitals {
  /** Heart rate, bpm */
  hr: number;
  /** Systolic blood pressure, mmHg */
  sbp: number;
  /** Diastolic blood pressure, mmHg */
  dbp: number;
  /** Respiratory rate, breaths/min */
  rr: number;
  /** Peripheral oxygen saturation, % */
  spo2: number;
  /** Temperature, °C */
  temp: number;
}

/**
 * Per-minute linear drift applied to the patient's arrival vitals as simulated
 * time advances. This is what makes "silent deterioration" observable in a demo
 * without waiting real hours. All zeroes = physiologically stable patient.
 */
export type VitalDrift = Partial<Record<keyof Vitals, number>>;

/**
 * How a patient's observations behave over the wait.
 *
 * An earlier revision used a bare linear ramp for everyone, which made
 * deterioration trivially detectable and the demo self-fulfilling: NEWS on a
 * monotonic ramp will always cross a threshold eventually. Real observations
 * are noisy, sometimes improve, and — most importantly — often are not taken
 * at all once the patient is in the waiting room.
 */
export interface VitalTrajectory extends VitalDrift {
  /** Deterministic per-vital jitter amplitude. Real obs are never a clean line. */
  noise?: VitalDrift;
  /**
   * Minute at which the drift changes — treatment works, or compensation fails.
   * After this point `after` replaces the primary drift.
   */
  inflectionMinutes?: number;
  after?: VitalDrift;
  /**
   * Minutes after arrival beyond which nobody re-measures. Observations freeze
   * at their last value and the UI marks them stale. This is the honest case:
   * a continuous re-scoring system is blind exactly when the data stops.
   */
  staleAfterMinutes?: number;
}

export type AcuityLevel = 1 | 2 | 3 | 4 | 5;

/**
 * Named, time-critical clinical risks the model may attach to a patient.
 *
 * A CLOSED vocabulary on purpose: the model picks from this list, the list maps
 * to fixed weights in urgency.ts, and nothing the model writes can invent a new
 * weight. This is the mechanism that makes the language model load-bearing —
 * an ESI-3 with an airway risk and an ESI-3 with a kidney stone carry the same
 * acuity number and are very different problems, and only free-text reasoning
 * over the narrative can tell them apart.
 */
export type RiskFactor =
  | "airway_compromise"
  | "neuro_red_flag"
  | "cardiac_ischaemia"
  | "thromboembolic"
  | "sepsis"
  | "haemorrhage"
  | "none";

export const RISK_FACTORS: RiskFactor[] = [
  "airway_compromise",
  "neuro_red_flag",
  "cardiac_ischaemia",
  "thromboembolic",
  "sepsis",
  "haemorrhage",
  "none",
];

export const RISK_FACTOR_LABEL: Record<RiskFactor, string> = {
  airway_compromise: "Airway compromise",
  neuro_red_flag: "Neurological red flag",
  cardiac_ischaemia: "Possible cardiac ischaemia",
  thromboembolic: "Thromboembolic risk",
  sepsis: "Sepsis risk",
  haemorrhage: "Haemorrhage risk",
  none: "None identified",
};

/** The structured object the local LLM is asked to return. */
export interface AiScore {
  acuity_level: AcuityLevel;
  /** 0..1 */
  confidence: number;
  /** 1-2 sentences, grounded in the given complaint + vitals. */
  rationale: string;
  atypical_presentation_flag: boolean;
  /** Vitals or history the model says it needed and did not get. */
  missing_information?: string;
  /** Optional free text explaining the atypical flag. */
  atypical_reason?: string;
  /** Named time-critical risks, each carrying a fixed weight in the urgency model. */
  risk_factors: RiskFactor[];
  /** Where the score came from. */
  source: "llm" | "heuristic-fallback";
  /** Model id that produced it (or "rule-based" for the fallback). */
  model: string;
  /** Wall-clock ms the scoring call took. */
  latencyMs: number;
  /** Real-world ISO timestamp of the scoring call. */
  scoredAt: string;
}

export interface OverrideRecord {
  id: string;
  patientId: string;
  fromAcuity: AcuityLevel;
  toAcuity: AcuityLevel;
  direction: "upgrade" | "downgrade";
  reason: string;
  nurse: string;
  /** Simulated-time minutes since ED "day start" at which the override happened. */
  atSimMinutes: number;
  /** True for overrides baked into the seed (historical shift data). */
  seeded: boolean;
}

export interface AmbientFlag {
  reason: string;
  /** 0..1 confidence of the simulated ambient-sensing layer. */
  confidence: number;
}

export interface Patient {
  id: string;
  /** Synthetic label, e.g. "R. Alvarez". Not a real person. */
  name: string;
  /**
   * Age and sex are the only person-level attributes recorded, and they are here
   * because they are clinically causal for risk — ACS presents differently by
   * both, and every triage scale in use is age-weighted. Nothing else about who
   * the patient is exists in this data model.
   */
  age: number;
  sex: Sex;
  arrivalMode: ArrivalMode;
  /**
   * What the hospital had on file before this arrival, or null for a
   * first-time patient. Roughly half the cohort is null, per the brief.
   */
  priorRecord: PriorRecord | null;
  /**
   * Vitals that could not be obtained at intake — a distressed child who will
   * not tolerate a cuff, an agitated patient, a queue moving too fast. Listed
   * here rather than silently defaulted, because a missing observation must
   * raise caution rather than score zero.
   */
  unobtainableVitals: (keyof Vitals)[];
  chiefComplaint: string;
  /** Extra context handed to the model (history, onset, etc.). */
  narrative: string;
  /** Vitals measured at arrival. */
  arrivalVitals: Vitals;
  trajectory: VitalTrajectory;
  /** Minutes since ED day start at which this patient arrived. */
  arrivalSimMinutes: number;
  ai: AiScore | null;
  /** Set while a scoring request is in flight. */
  scoring: boolean;
  scoringError: string | null;
  /** Nurse-assigned acuity, when overridden. Null = accept AI score. */
  overrideAcuity: AcuityLevel | null;
  ambient: AmbientFlag | null;
  /** Bed assignment from the flow-routing simulator. */
  assignedBed: string | null;
  /** The "ground truth" this synthetic case is meant to illustrate. Demo aid only. */
  teachingNote: string | null;
}

/** Per-patient values recomputed on every read at the current simulated time. */
export interface PatientSnapshot extends Patient {
  currentVitals: Vitals;
  /** Which early-warning chart applies to this patient's age. */
  ageBand: AgeBand;
  /** Name of the instrument used, for display. */
  ewsChart: string;
  /**
   * What these same observations would have scored on the adult chart. Shown
   * for non-adults to make the cost of a one-size-fits-all score visible.
   */
  adultChartNews: number;
  completeness: DataCompleteness;
  /** Minutes this acuity level is allowed to wait before mandatory review. */
  reassessDueAtMinutes: number;
  /** True once that interval has elapsed without a re-assessment. */
  reassessOverdue: boolean;
  /** How far past the safe interval, in simulated minutes. */
  reassessOverdueByMinutes: number;
  /** Simulated minutes since these observations were last actually taken. */
  vitalsAgeMinutes: number;
  /** True when nobody has re-measured this patient for a clinically long time. */
  vitalsStale: boolean;
  waitMinutes: number;
  news: number;
  newsBand: "low" | "medium" | "high";
  /** Acuity currently in force: override if present, else AI, else 3. */
  effectiveAcuity: AcuityLevel;
  urgency: number;
  urgencyAtArrival: number;
  urgencyBreakdown: UrgencyBreakdown;
  status: EscalationStatus;
  /** Sim-minute at which urgency first crossed the escalation threshold, if ever. */
  escalationCrossedAtMinutes: number | null;
  /** Rank in the queue (1 = seen first). */
  rank: number;
  /** rankAtArrival - rank. Positive = has moved up the queue. */
  rankDelta: number;
}

export interface UrgencyBreakdown {
  base: number;
  /**
   * Safety margin applied when the system is uncertain — low model confidence,
   * missing intake data, no prior record, or an age band where deterioration is
   * known to present late. Deliberately one-directional: it can only ever raise
   * urgency, because under-triage and over-triage do not cost the same.
   */
  precautionaryUplift: number;
  waitPressure: number;
  atypicalBoost: number;
  riskFactorBoost: number;
  ambientBoost: number;
  physiologyPressure: number;
  total: number;
  escalationRatePerMin: number;
}

export type EscalationStatus = "stable" | "watch" | "escalated" | "critical";

export interface AuditEvent {
  id: string;
  /** Real-world ISO timestamp. */
  at: string;
  atSimMinutes: number;
  kind:
    | "llm_request"
    | "llm_response"
    | "llm_error"
    | "llm_fallback"
    | "override"
    | "clock"
    | "seed"
    | "routing";
  patientId?: string;
  summary: string;
  /** Full request/response payloads for the demo's audit trail. */
  detail?: unknown;
}

export interface Bed {
  id: string;
  kind: "resus" | "acute" | "fast-track";
  /** Highest ESI level this bed is appropriate for (1 = can take anything). */
  minAcuity: AcuityLevel;
  occupiedBy: string | null;
}

export interface ClockState {
  /** Real Date.now() at the last clock mutation. */
  anchorRealMs: number;
  /** Simulated minutes since ED day start at the last clock mutation. */
  anchorSimMinutes: number;
  /** Simulated minutes elapsed per real second. 0 = paused. */
  rate: number;
}

export interface EquityGroupStat {
  tag: ArrivalMode;
  n: number;
  meanAiAcuity: number | null;
  meanFinalAcuity: number;
  meanNews: number;
  overrides: number;
  downgrades: number;
  upgrades: number;
  overrideRate: number;
  downgradeRate: number;
  /** Mean final acuity restricted to patients with NEWS >= 3 (severity-matched). */
  meanFinalAcuityHighNews: number | null;
  nHighNews: number;
}

export interface EquityFinding {
  metric: "final_acuity" | "downgrade_rate" | "severity_matched_acuity";
  tag: ArrivalMode;
  groupValue: number;
  comparisonValue: number;
  z: number;
  /** Two-sided p for this z, before correction. */
  pValue: number;
  /** True only if it survives the Benjamini-Hochberg correction across all tests. */
  notable: boolean;
  message: string;
}

/**
 * An override that moved a patient AWAY from what their own measured physiology
 * supported. Needs no grouping variable at all — each patient is compared only
 * against themselves, so this catches unsafe overrides without profiling anyone.
 */
export interface OverrideContradiction {
  overrideId: string;
  patientId: string;
  patientName: string;
  fromAcuity: AcuityLevel;
  toAcuity: AcuityLevel;
  /** NEWS computed at the simulated minute the override was recorded. */
  newsAtOverride: number;
  /** NEWS at the current simulated minute. */
  newsNow: number;
  reason: string;
  nurse: string;
  atSimMinutes: number;
}

export interface EquityReport {
  groups: EquityGroupStat[];
  findings: EquityFinding[];
  /** How many comparisons were run — the denominator for the FDR correction. */
  testsRun: number;
  contradictions: OverrideContradiction[];
  /** NEWS at or above which a downgrade counts as contradicting physiology. */
  contradictionNewsThreshold: number;
  cohortSize: number;
  generatedAtSimMinutes: number;
}

export interface SurgePoint {
  hour: number;
  label: string;
  actual: number | null;
  forecast: number;
  lower: number;
  upper: number;
}

export interface SurgeReport {
  points: SurgePoint[];
  windowSize: number;
  nextHourForecast: number;
  staffedCapacityPerHour: number;
  breachHours: number[];
  /** Index into `points[].hour` marking the current simulated hour. */
  nowHour: number;
}
